"""Failure mode taxonomy — auto-mined from 199 Nusuk incidents."""
# Format: FM-XXX: (name, affected_system, service, worst_severity, includes_keywords, excludes_keywords)
FAILURE_MODES: dict[str, tuple[str, str, str, str, str, str]] = {
    'FM-001': ('Database server CPU exceeds threshold', 'Other', 'General / Unspecified', 'Major', 
               'cpu,alert,threshold,usage,performance', ''),
    'FM-002': ('Housing confirmations cancelled due to incorrect pilgrim linkage', 'Nusuk Masar Haj', 'Housing Preference Services', 'Critical',
               'housing,confirm,cancel,accommodation,pilgrim', ''),
    'FM-003': ('Guide names not appearing during bus assignment', 'Nusuk Masar Haj', 'Istiqbal.Assign Guide to Bus', 'Major',
               'guide,bus,assign,appear', ''),
    'FM-004': ('CRM system operational failure reported', 'Other', 'General / Unspecified', 'Critical',
               'crm,system,failure,operational', ''),
    'FM-005': ('Payment transactions fail to credit bank or wallet', 'Nusuk Masar Haj', 'Financial Transactions.view tansactions list', 'Critical',
               'payment,transaction,fail,bank,wallet', ''),
    'FM-006': ('Pilgrim count mismatch between departure views', 'Nusuk Masar Haj', 'Financial Transactions.view tansactions list', 'Major',
               'pilgrim,count,mismatch,departure', ''),
    'FM-007': ('Company evaluation icon missing from interface', 'Nusuk Masar Haj', 'System/Application', 'Major',
               'evaluation,icon,missing,interface,cycle', ''),
    'FM-008': ('Resolved complaint status not updated to closed', 'Other', 'General / Unspecified', 'Minor',
               'complaint,status,close,update,resolved', ''),
    'FM-009': ('Permit status not updating after cancellation request', 'Nusuk Masar Haj', 'General / Unspecified', 'Major',
               'permit,status,update,cancel', ''),
    'FM-010': ('User cannot enter pilgrim numbers during registration', 'Nusuk Masar Haj', 'Between cities.Create between cities  Request', 'Critical',
               'pilgrim,register,enter,number,data', ''),
    'FM-011': ('Users blocked from accessing tax billing data update', 'Nusuk Masar Haj', 'Invoicing and Billing.Bill Payment', 'Major',
               'tax,billing,access,blocked,data', ''),
    'FM-012': ('User requests manual permit issuance after time', 'Nusuk Masar Haj', 'pilgrim groups and issue permit.Issue Permits', 'Major',
               'manual,permit,request,after,time,extend', 'suggestion,propose,feature'),
    'FM-013': ('Error code appears in boarding manifest report', 'Nusuk Masar Haj', 'Mashaeer Boarding Manifest Reports', 'Major',
               'boarding,manifest,error,code', ''),
    'FM-014': ('Users unable to reply to or close reports', 'Nusuk Masar Haj', 'inquiry', 'Major',
               'reply,close,report,inquiry,page,load', 'export,excel,csv'),
    'FM-015': ('Between cities request approval fails before departure', 'Nusuk Masar Haj', 'Between cities.Create between cities  Request', 'Major',
               'between,cities,approval,transport,inter-city', ''),
    'FM-016': ('User passport scanning fails due to permission mismatch', 'Nusuk Masar Haj', 'Istiqbal', 'Major',
               'passport,scan,permission,mismatch', ''),
    'FM-017': ('Registration rejects commercial not starting with 4', 'Nusuk Masar Haj', 'Registration', 'Major',
               'registration,commercial,reject,license,number', ''),
    'FM-018': ('Rawdah permit issuance fails on date selection', 'Nusuk Masar Haj', 'pilgrim groups and issue permit.Issue Permits', 'Critical',
               'rawdah,rawdha,permit,issue,date,appointment,booking', 'umrah,hajj,general'),
    'FM-019': ('Hotel registration fails at step 5 with contact support error', 'Nusuk Masar Haj', 'pilgrim groups and issue permit', 'Major',
               'hotel,registration,fail,step,accommodation', ''),
    'FM-020': ('Actual arrival confirmation fails for housing contract', 'Nusuk Masar Haj', 'contracts.Contract with Accommodation Service Providers', 'Major',
               'arrival,confirm,housing,contract,actual', ''),
    'FM-021': ('Appeal submission fails with data design error', 'Nusuk Masar Haj', 'suggestion', 'Major',
               'appeal,data,design,error,submission,نقترح,مقترح', ''),
    'FM-022': ('User cannot submit appeal request for violations', 'Nusuk Masar Haj', 'suggestion', 'Major',
               'appeal,violation,submit,تظلم,مخالفة', 'suggestion,propose,kpi,indicator,feature,نقترح'),
}
