"""Failure mode taxonomy — auto-mined from 199 Nusuk incidents."""
# Format: FM-XXX: (name, affected_system, service, worst_severity, includes_keywords, excludes_keywords)
FAILURE_MODES: dict[str, tuple[str, str, str, str, str, str]] = {
    'FM-001': ('Database server CPU exceeds threshold', 'Other', 'General / Unspecified', 'Major', 
               'cpu,alert,threshold,usage,performance', ''),
    'FM-002': ('Housing confirmations cancelled due to incorrect pilgrim linkage', 'Nusuk Masar Haj', 'Housing Preference Services', 'Critical',
               'housing,confirm,cancel,accommodation,pilgrim', ''),
    'FM-003': ('Guide names not appearing during bus assignment', 'Nusuk Masar Haj', 'Istiqbal.Assign Guide to Bus', 'Major',
               'guide,bus,assign,appear', ''),
    'FM-004': ('CRM system operational failure reported', 'Other', 'General / Unspecified', 'Critical',
               'crm,system,failure,operational', ''),
    'FM-005': ('Payment transactions fail to credit bank or wallet', 'Nusuk Masar Haj', 'Financial Transactions.view tansactions list', 'Critical',
               'payment,transaction,fail,bank,wallet', ''),
    'FM-006': ('Pilgrim count mismatch between departure views', 'Nusuk Masar Haj', 'Financial Transactions.view tansactions list', 'Major',
               'pilgrim,count,mismatch,departure', ''),
    'FM-007': ('Company evaluation icon missing from interface', 'Nusuk Masar Haj', 'System/Application', 'Major',
               'evaluation,icon,missing,interface,cycle', ''),
    'FM-008': ('Resolved complaint status not updated to closed', 'Other', 'General / Unspecified', 'Minor',
               'complaint,status,close,update,resolved', ''),
    'FM-009': ('Permit status not updating after cancellation request', 'Nusuk Masar Haj', 'General / Unspecified', 'Major',
               'permit,status,update,cancel', ''),
    'FM-010': ('User cannot enter pilgrim numbers during registration', 'Nusuk Masar Haj', 'Between cities.Create between cities  Request', 'Critical',
               'pilgrim,register,enter,number,data', ''),
    'FM-011': ('Users blocked from accessing tax billing data update', 'Nusuk Masar Haj', 'Invoicing and Billing.Bill Payment', 'Major',
               'tax,billing,access,blocked,data', ''),
    'FM-012': ('User requests manual permit issuance after time', 'Nusuk Masar Haj', 'pilgrim groups and issue permit.Issue Permits', 'Major',
               'manual,permit,request,after,time,extend', 'suggestion,propose,feature'),
    'FM-013': ('Error code appears in boarding manifest report', 'Nusuk Masar Haj', 'Mashaeer Boarding Manifest Reports', 'Major',
               'boarding,manifest,error,code', ''),
    'FM-014': ('Users unable to reply to or close reports', 'Nusuk Masar Haj', 'inquiry', 'Major',
               'reply,close,report,inquiry,page,load', 'export,excel,csv'),
    'FM-015': ('Between cities request approval fails before departure', 'Nusuk Masar Haj', 'Between cities.Create between cities  Request', 'Major',
               'between,cities,approval,transport,inter-city', ''),
    'FM-016': ('User passport scanning fails due to permission mismatch', 'Nusuk Masar Haj', 'Istiqbal', 'Major',
               'passport,scan,permission,mismatch', ''),
    'FM-017': ('Registration rejects commercial not starting with 4', 'Nusuk Masar Haj', 'Registration', 'Major',
               'registration,commercial,reject,license,number', ''),
    'FM-018': ('Rawdah permit issuance fails on date selection', 'Nusuk Masar Haj', 'pilgrim groups and issue permit.Issue Permits', 'Critical',
               'rawdah,rawdha,permit,issue,date,appointment,booking', 'umrah,hajj,general'),
    'FM-019': ('Hotel registration fails at step 5 with contact support error', 'Nusuk Masar Haj', 'pilgrim groups and issue permit', 'Major',
               'hotel,registration,fail,step,accommodation', ''),
    'FM-020': ('Actual arrival confirmation fails for housing contract', 'Nusuk Masar Haj', 'contracts.Contract with Accommodation Service Providers', 'Major',
               'arrival,confirm,housing,contract,actual', ''),
    'FM-021': ('Appeal submission fails with data design error', 'Nusuk Masar Haj', 'suggestion', 'Major',
               'appeal,data,design,error,submission,نقترح,مقترح', ''),
    'FM-022': ('User cannot submit appeal request for violations', 'Nusuk Masar Haj', 'suggestion', 'Major',
               'appeal,violation,submit,تظلم,مخالفة', 'suggestion,propose,kpi,indicator,feature,نقترح'),
}

# Signature → FM code hints for classifier prompt
SIGNATURE_HINTS: dict[str, str] = {
    'Database server CPU exceeds threshold': 'FM-001',
    'Database server CPU exceeds threshold': 'FM-001',
    'Database server CPU exceeds threshold': 'FM-001',
    'Housing confirmations cancelled due to incorrect pilgrim lin': 'FM-002',
    'Housing confirmations cancelled due to incorrect pilgrim lin': 'FM-002',
    'Housing confirmations cancelled due to incorrect pilgrim lin': 'FM-002',
    'Guide names not appearing during bus assignment': 'FM-003',
    'Cannot add replacement buses after cancellation': 'FM-003',
    'User can\'t assign guide to bus after data': 'FM-003',
    'CRM system operational failure reported': 'FM-004',
    'CRM system fails to operate': 'FM-004',
    'CRM system experiencing operational failure': 'FM-004',
    'Financial transactions failing status update': 'FM-005',
    'Internal invoice transfers to hotel bank accounts failing': 'FM-005',
    'Payment transactions fail to credit bank or wallet': 'FM-005',
    'Financial transaction amounts mismatch with approved contrac': 'FM-006',
    'Pilgrim count mismatch between departure views': 'FM-006',
    'Financial transaction amount does not match contract total': 'FM-006',
    'Departure field missing from Hajj data screen': 'FM-007',
    'Supervisor cannot see company evaluation cycles tab': 'FM-007',
    'Evaluation icon missing from supervisor account menu': 'FM-007',
    'Resolved complaint status not updated to closed': 'FM-008',
    'Resolved complaint remains active in system status': 'FM-008',
    'Report closure not updating in platform': 'FM-008',
    'Ticket status not updating after user closure': 'FM-009',
    'Permit status not updating after cancellation request': 'FM-009',
    'External ticket remains open after user closure': 'FM-009',
    'User can\'t add pilgrims to departure manifests': 'FM-010',
    'User unable to issue permits for external pilgrims': 'FM-010',
    'Pilgrim data field missing after trip selection': 'FM-010',
    'Users blocked from accessing tax billing data update': 'FM-011',
    'User gets access denied filling tax form': 'FM-011',
    'User unable to submit tax data form': 'FM-011',
    'User requests manual permit issuance after time': 'FM-012',
    'User requests copy of past season contract': 'FM-012',
    'User requests rental contract details for permit': 'FM-012',
    'Error code appears in boarding manifest report': 'FM-013',
    'Boarding manifest screen shows error after permission reques': 'FM-013',
    'System error during boarding check process': 'FM-013',
    'Users unable to reply to or close reports': 'FM-014',
    'Reports page not loading for service provider': 'FM-014',
    'System fails to receive submitted reports': 'FM-014',
    'Between cities request approval fails before departure': 'FM-015',
    'Pending inter-city travel requests require manual approval': 'FM-015',
    'Transport request approval fails before departure': 'FM-015',
    'User passport scanning fails due to permission mismatch': 'FM-016',
    'User cannot update passport information due to system error': 'FM-016',
    'Departure request fails due to passport mismatch': 'FM-016',
    'Registration rejects commercial not starting with 4': 'FM-017',
    'System rejects valid commercial registration during license ': 'FM-017',
    'System rejects valid license during submission': 'FM-017',
    'Rawdah permit issuance fails on date selection': 'FM-018',
    'Rawdah permits not showing in system for date': 'FM-018',
    'Rawdha Sharif appointment booking fails with error': 'FM-018',
    'Booking fails with error at confirmation step': 'FM-019',
    'Accommodation registration fails with communication error at': 'FM-019',
    'Hotel registration fails at step 5 with contact support erro': 'FM-019',
    'User cannot confirm actual arrival status for accommodation ': 'FM-020',
    'Provider cannot update actual arrival status': 'FM-020',
    'Actual arrival confirmation fails for housing contract': 'FM-020',
    'Appeal submission fails with data design error': 'FM-021',
    'Appeal submission fails with generic error message': 'FM-021',
    'Appeal submission blocked by validation error': 'FM-021',
    'User cannot submit appeal request for violations': 'FM-022',
    'User can\'t submit violation appeal due to data error': 'FM-022',
    'User can\'t submit appeal response for violation': 'FM-022',
}
