apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-classifier.fullname" . }}-api
  labels:
    {{- include "ai-classifier.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
  selector:
    {{- include "ai-classifier.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
